pipeline {
    agent any

options {
        timestamps()
        skipDefaultCheckout(true)
	}
    stages {
    
        stage('Clone github repository') {
            steps {
                cleanWs()
                sh 'git clone -b develop https://github.com/kittitereh/mle-hw1.git'
				}
			}


        stage('Create and run docker container') {
            steps {
                script {
                    try {
                        sh 'cd mle-hw1 && docker-compose build'
                        }

                    finally {
                    sh '''
                        cd mle-hw1
                        docker-compose up -d
                        '''
                        }
				    }
                }
            }



        stage('Docker login'){
        
            environment {
                BITBUCKET_COMMON_CREDS = credentials('5dbe3482-2e8f-4bbb-a794-2cb838bc0d21')
                }
            steps{
                sh('docker login -u ${BITBUCKET_COMMON_CREDS_USR} -p ${BITBUCKET_COMMON_CREDS_PSW}')
            }
        }
	
        stage('Push'){
            steps{
                sh 'docker push kittitereh/mle-hw1:latest'
            }
        }
    }

    post {
        always {
            sh 'docker logout'
        }
    }
    
}
    
